filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    json.message_key: log
    json.add_error_key: true
    json.keys_under_root: true

processors:
  - add_docker_metadata: ~
  - drop_fields:
      fields: ["host", "ecs", "agent"]

output.logstash:
  hosts: ["logstash:5044"]
