{
 "title": "Метрики Node Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[2m]))*100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free RAM (MB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FS Available (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}